### ISSUE TITLE
#03 議事録

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-jp/weekly#2]
# 開催日時

2020年04月17日 20時より

# 会場URL

Googleハングアウト: <https://hangouts.google.com/call/qAWPAkGi5b05uxFBJpDgAEEE> (終了しました)
HackMD: <https://hackmd.io/@3pgROSRCQByPU9KK45aHaA/B1BZ2WPdI/>

# 参加者

- [@MakeNowJust][] (主催)
- [@at-grandpa][]
- [@arcage][]

[@MakeNowJust]: https://github.com/MakeNowJust
[@at-grandpa]: https://github.com/at-grandpa
[@arcage]: https://github.com/arcage

# 注意

参加したい方は事前にこのissueに「参加します」などとコメントをください。
主催が拾って、上のリストに追加していきます。

**Comment by at-grandpa** [comment]
参加します！

**Comment by arcage** [comment]
参加できそうです。
