### ISSUE TITLE
#04 議事録

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-jp/weekly#3]
# 開催日時

2020年04月24日 20時より

# 会場

Issue (議事録): <https://github.com/crystal-jp/issues/3>
Googleハングアウト: <https://hangouts.google.com/call/OfTRh6Ue-LmSq9OcSPcvAEEM> (終了済み)
HackMD: <https://hackmd.io/@3pgROSRCQByPU9KK45aHaA/S1_klBeKI>

# 参加者

- [@MakeNowJust][] (主催)
- [@at-grandpa][]
- [@TobiasGSmollett][]
- [@arcage][]

[@MakeNowJust]: https://github.com/MakeNowJust
[@at-grandpa]: https://github.com/at-grandpa
[@TobiasGSmollett]: https://github.com/TobiasGSmollett
[@arcage]: https://github.com/arcage

# 注意

このissueはWeekly Crystal #04の準備・開催のためのものです。
ここで、参加表明や注意喚起などを行います。

参加したい方は事前にこのissueに「参加します」などとコメントをください。
主催が拾って、上のリストに追加していきます。

**Comment by at-grandpa** [comment]
参加しますー

**Comment by TobiasGSmollett** [comment]
参加しますー

**Comment by MakeNowJust** [comment]
@at-grandpa @TobiasGSmollett GoogleハングアウトのURLを追加しました。入ってきてください。
